apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vue-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fpicot31/k8s_ArgoCD.git
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
